// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class AchievementsConstants
{
        public const string achievement_interrupted_ending = "CgkIvon-9KIPEAIQBQ"; // <GPGSID>
        public const string achievement_throw_out_ending = "CgkIvon-9KIPEAIQBg"; // <GPGSID>
        public const string achievement_fire_ending = "CgkIvon-9KIPEAIQBA"; // <GPGSID>
        public const string achievement_patient_ending = "CgkIvon-9KIPEAIQAQ"; // <GPGSID>
        public const string achievement_impatient_ending = "CgkIvon-9KIPEAIQAg"; // <GPGSID>
        public const string achievement_dirty_ending = "CgkIvon-9KIPEAIQBw"; // <GPGSID>
        public const string achievement_violent_ending = "CgkIvon-9KIPEAIQAw"; // <GPGSID>

}

